### PR TITLE
Code quality, fix bug, added chained methods, added new BDD methods.

### LINKED ISSUE #48: Empty `specify()` and `describe()` blocks pass tests
The documentation states that `specify()` and `describe()` calls that don't pass anything to `$fn` will be marked as incomplete, but when I run them they are marked OK. These tests should either fail or be marked as risky to ensure that at least _some_ assertions are being made.

`$this->specify('some test');`

CLI output:

`ExampleTest     ✔︎  ✔︎  ✔︎  ✔︎  ✔︎ `

### PR DESCRIPTION
**Pull request by TavoNiievez**
fixes #48 .

**Code Quality:**
- [x] Specify public API now lives inside `Specify.php`, and private properties and methods inside `Specify\SpecifyBoostrap.php` for clarity and readability.
- [x] Added validations regarding whether the anonymous function is received as argument, and improved the names of the arguments depending on the called function.

**Once and for all:**
- [x] Enabled the feature described in the documentation that marks a test as incomplete if the _**it/should**_ only receives the description text without any anonymous function ( #48 ).

**Good things, even better:**
- [x] Added _**Fluent Interface**_ support, this allows you to add `it`'s and `should`'s chained to a `specify` or `describe`. In this way, this example code:
```php
    $this->describe("user", function() {
        $this->it("should have a name", function() {
            // do some asserts
        });

        $this->it("should not have long name", function() {
            // do more asserts
        });
    });
```
can now be written like this:
```php
    $this->describe('user')
        ->it('should have a name', function() {
            // do some asserts
        })
        ->shouldNot('have long name', function() {
            // do more asserts
        })
    ;
```
**Specify is smarter:**
- [x] Added alias `its` for `it`, and added `shouldNot` as counterpart of `should`
- [x] Added `.phpunit.result.cache` file to `.gitignore`

**Getting started:**
- As soon as this PR is merged, I will continue to add improvements to the tests and the other files inside the `Codeception/Specify` folder.
- Some changes may require additional documentation, so improving the docs is one of the goals in sight in future commits.

@DavertMik , @Naktibalda I'll pay attention to your comments.

### CODE REVIEW

**Comment by Naktibalda** [comment]
So many changes, I will try to understand what was changed another day.

**Comment by TavoNiievez** [comment]
they are in fact less than they appear to be.

- `Specify.php` now has the public functions: `specify`, `describe`, `it` and `should`.
- Whereas `Specify/ObjectProperty.php` has the rest of the private functions and attributes.
- The functions `specify`, `describe`, `it` and `should` now `return $this;` to allow chained statements, and as I specified,
- If an `it` or `should` only receives text now that test is marked as incomplete.
- `shouldNot` and `its` were added as aliases.

If you need more help reviewing the changes, please let me know, I'll be as explicit as possible.
I know it takes time but I hope the benefits justify the time spent.

File: src/Codeception/Specify.php [hunk 1]
```diff
@@ -1,224 +1,70 @@
...
-     * @throws \RuntimeException
-     */
-    private function getSpecifyExamples($params)
-    {
-        if (isset($params['examples'])) {
-            if (!is_array($params['examples'])) throw new \RuntimeException("Examples should be an array");
-            return $params['examples'];
-        }
-        return [[]];
+    use SpecifyBoostrap {
```
Comment (DavertMik) [inline src/Codeception/Specify.php:11]: Bootstrap maybe?

File: src/Codeception/Specify/SpecifyBoostrap.php [hunk 2]
```diff
@@ -0,0 +1,227 @@
...
+use Closure;
+use DeepCopy\DeepCopy;
+use PHPUnit\Framework\TestCase;
+use ReflectionClass;
+use ReflectionException;
+use ReflectionObject;
+use ReflectionProperty;
+use RuntimeException;
+
+trait SpecifyBoostrap
```
Comment (DavertMik) [inline src/Codeception/Specify/SpecifyBoostrap.php:14]: Bootstrap?

**Review by DavertMik — APPROVED** [review]
Thanks, looks good to me, except naming things 😁
If you want to improve specify I would be glad to give all my support with it. As long as tests pass feel free to improve it.

Btw, please join Codeception Slack channel so we could discuss big changes like this upfront. When you are there - text me privately.

File: src/Codeception/Specify.php (hunk 1 above)
Comment (DavertMik) [inline src/Codeception/Specify.php:11]: What about this naming:

`SpecifyHooks`

Before and After are hooks, we can name it like this
